---
# Playbook is a list of plays, always starting with -
- name: ping the node
  hosts: mongodb
  # This is a list of tasks/modules/collections
  tasks:
  - name: pinging the server
    # This is a map, ensure proper indentation
    ansible.builtin.ping:

