- name: variables from files
  hosts: localhost  # Managing the Ansible server itself
  vars_files:
    - gsp.yaml

  tasks:
    - name: printing variables
      ansible.builtin.debug:
        msg: "we are learning {{ NAME }}, Duration is: {{ DURATION }}, Trainer is: {{ TRAINER }}"
