- name: variables at taks level
  hosts: localhost
  # there variables of parent or play level
  vars:
  - money: "10000 RS"
    land: "100 hectars"
  tasks:
  - name: inherit values from play
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}"
  - name: inherit values from play and add and override
    vars:
    - money: "20000 RS"
      houses: "3 houses"
    ansible.builtin.debug:
      msg : "MONEY: {{money}}, LAND: {{land}} houses: {{houses}}"