- name: ansible variable data types
  hosts: localhost
  vars:
    AGE: 30 # Number
    NAME: "Sivakumar" # String
    isDevOps: True # Boolean
    Skills: # List
      - DevOps
      - AWS
      - Docker
    EXPERIENCE: # Dictionary
      DevOps: 7
      AWS: 5
      Docker: 4
  tasks:
    - name: print number variable
      ansible.builtin.debug:
        msg: "{{ AGE }}"
    - name: print string variables
      ansible.builtin.debug:
        msg: "{{ NAME }}"
    - name: print boolean variable
      ansible.builtin.debug:
        msg: "{{ isDevOps }}"
    - name: print list variable
      ansible.builtin.debug:
        msg: "{{ Skills }}"
    - name: print map variable
      ansible.builtin.debug:
        msg: "{{ EXPERIENCE }}"
