- name: create user
  hosts: localhost
  tasks:
    - name: check roboshop user exist or not
    # when you want to run linux commands directly ie.e. in the case ansible module not available
    # when the user does not exists, ansible treating this failure and comput by default
    # ignore_errors: true
      ansible.builtin.command: id roboshop
      register: output
      ignore_errors: true

    - name: print the command output # output is variable name is here
      ansible.builtin.debug:
        msg: "output is: {{output}}"
    - name: print exit status
      ansible.builtin.debug:
        msg: "output is: {{output.rc}}"
